ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER catalog_app IDENTIFIED BY catalog_app_dev_password
    DEFAULT TABLESPACE users
    QUOTA UNLIMITED ON users;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE TRIGGER
    TO catalog_app;

CREATE USER pricing_app IDENTIFIED BY pricing_app_dev_password
    DEFAULT TABLESPACE users
    QUOTA UNLIMITED ON users;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE TRIGGER
    TO pricing_app;
