nameOverride: ""
fullnameOverride: ""

image:
  registry: localhost:5000/modaprezzo
  tag: local
  pullPolicy: IfNotPresent

database:
  url: jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
  createSecret: true
  secretName: modaprezzo-db
  walletSecretName: ""
  walletMountPath: /etc/oracle/wallet
  catalogPassword: catalog_app_dev_password
  pricingPassword: pricing_app_dev_password

kafka:
  bootstrapServers: kafka:9092
  auth:
    enabled: false
    secretName: modaprezzo-kafka
    jaasConfigKey: sasl-jaas-config

ingress:
  enabled: false
  className: ""
  host: modaprezzo.local

services:
  catalog-service:
    image: catalog-service
    port: 8081
    replicas: 1
    databaseUser: catalog_app
    databasePasswordKey: catalog-password
    env:
      SERVER_PORT: "8081"
  pricing-service:
    image: pricing-service
    port: 8082
    replicas: 1
    databaseUser: pricing_app
    databasePasswordKey: pricing-password
    env:
      SERVER_PORT: "8082"
      CATALOG_BASE_URL: http://modaprezzo-catalog-service:8081
  assortment-ui-service:
    image: assortment-ui-service
    port: 8080
    replicas: 1
    env:
      SERVER_PORT: "8080"
      CATALOG_BASE_URL: http://modaprezzo-catalog-service:8081
      PRICING_BASE_URL: http://modaprezzo-pricing-service:8082
