image:
  registry: replace-with-region.ocir.io/replace-with-tenancy-namespace/modaprezzo
  tag: 0.1.0-SNAPSHOT
  pullPolicy: IfNotPresent

database:
  url: jdbc:oracle:thin:@replace-with-exadata-service-name_high?TNS_ADMIN=/etc/oracle/wallet
  createSecret: false
  secretName: modaprezzo-db
  walletSecretName: modaprezzo-db-wallet
  walletMountPath: /etc/oracle/wallet

kafka:
  bootstrapServers: replace-with-oci-streaming-kafka-bootstrap:9092
  auth:
    enabled: true
    secretName: modaprezzo-kafka
    jaasConfigKey: sasl-jaas-config

ingress:
  enabled: true
  className: native-ic-ingress-class
  host: replace-with-approved-hostname.example.com
