{{- if .Values.database.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
  labels:
    {{- include "modaprezzo.labels" . | nindent 4 }}
type: Opaque
stringData:
  catalog-password: {{ .Values.database.catalogPassword | quote }}
  pricing-password: {{ .Values.database.pricingPassword | quote }}
{{- end }}
