{{- range $serviceName, $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "modaprezzo.fullname" $ }}-{{ $serviceName }}
  labels:
    {{- include "modaprezzo.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $serviceName }}
  ports:
    - name: http
      port: {{ $service.port }}
      targetPort: http
---
{{- end }}
